/*
 * This source file was generated by the Gradle 'init' task
 */
package com.toedter.movies;

public class App {
    public static void main(String[] args) throws Exception {
        System.setProperty("webdriver.chrome.driver", "D:\\dev\\chrome\\chromedriver-win64\\chromedriver-win64\\chromedriver.exe");
        MovieScraper movieScraper = new MovieScraper();
        movieScraper.getMovies();
    }
}
